version: 2
jobs: 
  build: # runs not using Workflows must have a `build` job as entry point 
    working_directory: ~/tomato_wallet_back_end
    docker: # run the steps with Docker
      - image: python:3.7.3
      - image: postgres:11.2 
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: tomato_wallet
          POSTGRES_PASSWORD: ""

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - restore_cache:
          key: v1
      - run: |
          if [ ! -d "/root/venv" ]; then
            python3 -m venv ~/venv
          fi
          . ~/venv/bin/activate
          pip install -r requirements/test.txt
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: v1
          paths:
           - "~/.cache/pip"
           - "~/venv"
      - run:
          command: |
            . ~/venv/bin/activate
            PYTEST_ADDOPTS="--junit-xml=~/artifacts/junit.xml --dc=Test --create-db" \
            python manage.py test
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
