# Generated by Django 2.2 on 2019-04-25 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190422_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
