# Generated by Django 2.2 on 2019-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20190425_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
